---
  - hosts:
      - tag_Name_prod_server
    become: yes
    gather_facts: yes
    tasks:
      - name: WROTE WELCOME MESSAGE TO PROD SERVER
        ansible.builtin.template:
          src: welcome_message.j2
          dest: /etc/profile.d/welcome_message.sh
          owner: root
          group: root
          mode: '0644'

      - name: STARTED DOCKER ENGINE ON PROD SERVER
        ansible.builtin.shell: sudo systemctl start docker

      - name: CLONED DIRECTION APP CODE FROM GITHUB MAIN BRANCH
        ansible.builtin.git:
          repo: https://github.com/olaniyikolawole744/devops-penultimante-project.git
          dest: /tmp/project
          separate_git_dir: /tmp/projectbakup2

      - name: LOGGED IN TO DOCKERHUB
        docker_login:
          registry_url: https://registry.hub.docker.com
          username: "{{ dockerhubusername }}"
          password: "{{ dockerhubpassword }}"
          reauthorize: yes

      - name: BUILT DIRECTION APP IMAGE FOR PROD SERVER AND PUSH IMAGE TO DOCKERHUB
        docker_image:
          build:
            path: /tmp/project/code
            dockerfile: Dockerfile
            pull: yes
          source: build
          push: yes
          name: registry.hub.docker.com/olaniyikolawole744/direction-prod
          tag: 2.0

#      - name: PULL DIRECTION APP IMAGE FROM DOCKERHUB
#        docker_image:
#          name: olaniyikolawole744/direction-prod
#          tag: 1.0
#          source: pull
#          repository: registry.hub.docker.com/olaniyikolawole744/direction-prod

      - name: DEPLOY DIRECTION APP CONTAINER ON PROD SERVER
        ansible.builtin.shell: sudo  docker run --name direction-prod:2 -d -p 8080:8080 -e loginname=myname -e loginpass=mypass -e api_key=*****  olaniyikolawole744/direction-prod:2.0
